description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^1.0.5"
  path_drawing: "^1.0.0"
  flutter: 
    sdk: "flutter"
  firebase_core: ^2.13.1
  firebase_messaging: ^14.6.2
  http:
  
  path_provider: ^2.0.15
  grock: ^0.0.4+2
  
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.12.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Inter"
      fonts: 
        - 
          asset: "fonts/Inter-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
