import 'package:flutter/material.dart';

/* UndefinedNode form field
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFormfieldWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(child: Container());
  }
}
