// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMUCfcH0WFqywWDS5hOGx1MqTAVR2nFY',
    appId: '1:35604273231:web:43fb94f2ed31cfe8bf723a',
    messagingSenderId: '35604273231',
    projectId: 'awish-65b44',
    authDomain: 'awish-65b44.firebaseapp.com',
    storageBucket: 'awish-65b44.appspot.com',
    measurementId: 'G-8KEK35P7Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkriZqHlLa_HwojxaAdz8PNKaa78xm0w',
    appId: '1:35604273231:android:ea87f2b48f229284bf723a',
    messagingSenderId: '35604273231',
    projectId: 'awish-65b44',
    storageBucket: 'awish-65b44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_EQhpO_BQeZHQJbSp515EWbw4zirE9Fc',
    appId: '1:35604273231:ios:36fbbd0e01bf6748bf723a',
    messagingSenderId: '35604273231',
    projectId: 'awish-65b44',
    storageBucket: 'awish-65b44.appspot.com',
    iosClientId: '35604273231-fi8u3b62qo633ahd2hblonksrvomkcoc.apps.googleusercontent.com',
    iosBundleId: 'com.example.helloWorld',
  );
}
