import 'package:flutter/material.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedRectangle2Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedDESSERTWidget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedORDERWidget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedRectangle4Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedPngwing5Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedTEAWidget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedCOFFEEWidget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedWATERWidget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedPngwing1Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedPngwing2Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/awishapp/generatedandroidlarge1widget/generated/GeneratedPngwing6Widget.dart';

import '../../service.dart';

/* Frame Android Large - 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedAndroidLarge1Widget extends StatefulWidget {
  @override
  State<GeneratedAndroidLarge1Widget> createState() =>
      _GeneratedAndroidLarge1Widget();
}

class _GeneratedAndroidLarge1Widget
    extends State<GeneratedAndroidLarge1Widget> {
  final _service = FirebaseNotificationService();
  @override
  void initState() {
    super.initState();
    _service.connectNotification();
  }

  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 18.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 41.0,
                child: GeneratedRectangle1Widget(),
              ),
              Positioned(
                left: 226.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 3.0,
                height: 1.0,
                child: GeneratedRectangle2Widget(),
              ),
              Positioned(
                left: 66.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 234.0,
                height: 25.0,
                child: GeneratedTEAWidget(),
              ),
              Positioned(
                left: 17.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 41.0,
                child: GeneratedRectangle3Widget(),
              ),
              Positioned(
                left: 17.0,
                top: 569.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 41.0,
                child: GeneratedRectangle6Widget(),
              ),
              Positioned(
                left: 205.0,
                top: 666.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 41.0,
                child: GeneratedRectangle7Widget(),
              ),
              Positioned(
                left: 18.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 325.0,
                height: 41.0,
                child: GeneratedRectangle4Widget(),
              ),
              Positioned(
                left: 63.0,
                top: 262.0,
                right: null,
                bottom: null,
                width: 237.0,
                height: 32.0,
                child: GeneratedCOFFEEWidget(),
              ),
              Positioned(
                left: 44.0,
                top: 430.0,
                right: null,
                bottom: null,
                width: 276.0,
                height: 46.0,
                child: GeneratedWATERWidget(),
              ),
              Positioned(
                left: 136.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 80.0,
                height: 61.67938995361328,
                child: GeneratedPngwing1Widget(),
              ),
              Positioned(
                left: 113.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 47.0,
                child: GeneratedPngwing2Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 573.0,
                right: null,
                bottom: null,
                width: 284.0,
                height: 37.0,
                child: GeneratedDESSERTWidget(),
              ),
              Positioned(
                left: 159.0,
                top: 499.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 69.95872497558594,
                child: GeneratedPngwing5Widget(),
              ),
              Positioned(
                left: 155.0,
                top: 342.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 85.0,
                child: GeneratedPngwing6Widget(),
              ),
              Positioned(
                left: 207.0,
                top: 669.0,
                right: null,
                bottom: null,
                width: 134.0,
                height: 41.0,
                child: GeneratedORDERWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 662.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 49.0,
                child: GeneratedRectangle8Widget(),
              )
            ]),
      ),
    ));
  }
}
